# Generated by Django 4.2.11 on 2024-03-29 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_and_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Postal code must be in the format XXX XXX or XXXXX-XXXX or XXXXX.', regex='(^\\d{5}(-\\d{4})?$)|([A-Za-z]\\d[A-Za-z] ?\\d[A-Za-z]\\d)')]),
        ),
    ]
