# Generated by Django 4.2.11 on 2024-03-29 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_and_promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 5, 24, 12, 665946, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
