# Generated by Django 4.2.11 on 2024-03-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Details', 'verbose_name_plural': 'Order Details'},
        ),
    ]
